function devhttpclient(){var db='',mb='" for "gwt:onLoadErrorFn"',kb='" for "gwt:onPropertyErrorFn"',nb='#',Ab='.cache.js',pb='/',vb='//',yb='55133F8F24CBB8C06A318E8F56082985',zb=':',eb='::',Pb=':moduleBase',hb='=',ob='?',jb='Bad handler "',X='DOMContentLoaded',U='DUMMY',Ob='Ignoring non-whitelisted Dev Mode URL: ',Nb='__gwtDevModeHook:devhttpclient',ub='base',sb='baseUrl',P='begin',V='body',O='bootstrap',rb='clear.cache.gif',gb='content',Hb='css/bootstrap.min.css',Jb='css/font-awesome.css',Ib='css/gwt-bootstrap.css',S='devhttpclient',xb='devhttpclient.devmode.js',tb='devhttpclient.nocache.js',cb='devhttpclient::',Kb='end',Mb='file:',Q='gwt.codesvr.devhttpclient=',R='gwt.codesvr=',lb='gwt:onLoadErrorFn',ib='gwt:onPropertyErrorFn',fb='gwt:property',Fb='head',Eb='href',Lb='http:',qb='img',Z='javascript',Bb='link',Gb='loadExternalRefs',ab='meta',_='moduleRequested',$='moduleStartup',bb='name',Cb='rel',Y='script',wb='selectingPermutation',T='startup',Db='stylesheet',W='undefined';var n=window;var o=document;q(O,P);function p(){var a=n.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function q(a,b){if(n.__gwtStatsEvent){n.__gwtStatsEvent({moduleName:S,sessionId:n.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
devhttpclient.__sendStats=q;devhttpclient.__moduleName=S;devhttpclient.__errFn=null;devhttpclient.__moduleBase=U;devhttpclient.__softPermutationId=0;devhttpclient.__computePropValue=null;devhttpclient.__getPropMap=null;devhttpclient.__gwtInstallCode=function(){};devhttpclient.__gwtStartLoadingFragment=function(){return null};var r=function(){return false};var s=function(){return null};__propertyErrorFunction=null;var t=n.__gwt_activeModules=n.__gwt_activeModules||{};t[S]={moduleName:S};var u;function v(){A();return u}
function w(){A();return u.getElementsByTagName(V)[0]}
function A(){if(u){return}u=n.document;if(!u){u=n.document}}
function B(f){function g(a){function b(){if(typeof o.readyState==W){return typeof o.body!=W&&o.body!=null}return /loaded|complete/.test(o.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(o.removeEventListener){o.removeEventListener(X,d,false)}if(e){clearInterval(e)}}}
if(o.addEventListener){o.addEventListener(X,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function h(a){var b=w();var c=v().createElement(Y);c.language=Z;c.src=a;q($,_);b.appendChild(c)}
g(function(){h(f)})}
devhttpclient.__startLoadingFragment=function(a){return F(a)};devhttpclient.__installRunAsyncCode=function(a){var b=w();var c=v().createElement(Y);c.language=Z;c.text=a;b.appendChild(c);b.removeChild(c)};function C(){var c={};var d;var e;var f=o.getElementsByTagName(ab);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(bb),k;if(j){j=j.replace(cb,db);if(j.indexOf(eb)>=0){continue}if(j==fb){k=i.getAttribute(gb);if(k){var l,m=k.indexOf(hb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=db}c[j]=l}}else if(j==ib){k=i.getAttribute(gb);if(k){try{d=eval(k)}catch(a){alert(jb+k+kb)}}}else if(j==lb){k=i.getAttribute(gb);if(k){try{e=eval(k)}catch(a){alert(jb+k+mb)}}}}}s=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;devhttpclient.__errFn=e}
function D(){function e(a){var b=a.lastIndexOf(nb);if(b==-1){b=a.length}var c=a.indexOf(ob);if(c==-1){c=a.length}var d=a.lastIndexOf(pb,Math.min(c,b));return d>=0?a.substring(0,d+1):db}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=o.createElement(qb);b.src=a+rb;a=e(b.src)}return a}
function g(){var a=s(sb);if(a!=null){return a}return db}
function h(){var a=o.getElementsByTagName(Y);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(tb)!=-1){return e(a[b].src)}}return db}
function i(){var a=o.getElementsByTagName(ub);if(a.length>0){return a[a.length-1].href}return db}
function j(){var a=o.location;return a.href==a.protocol+vb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==db){k=h()}if(k==db){k=i()}if(k==db&&j()){k=e(o.location.href)}k=f(k);return k}
function F(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return devhttpclient.__moduleBase+a}
function G(){var f=[];var g;var h=[];var i=[];function j(a){var b=i[a](),c=h[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
r=function(a,b){return b in h[a]};devhttpclient.__getPropMap=function(){var a={};for(var b in h){if(h.hasOwnProperty(b)){a[b]=j(b)}}return a};devhttpclient.__computePropValue=j;n.__gwt_activeModules[S].bindings=devhttpclient.__getPropMap;q(O,wb);if(p()){return F(xb)}var k;try{k=yb;var l=k.indexOf(zb);if(l!=-1){g=parseInt(k.substring(l+1),10);k=k.substring(0,l)}}catch(a){}devhttpclient.__softPermutationId=g;return F(k+Ab)}
function H(){if(!n.__gwt_stylesLoaded){n.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=o.createElement(Bb);b.setAttribute(Cb,Db);b.setAttribute(Eb,F(a));o.getElementsByTagName(Fb)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
q(Gb,P);c(Hb);c(Ib);c(Jb);q(Gb,Kb)}
C();devhttpclient.__moduleBase=D();t[S].moduleBase=devhttpclient.__moduleBase;var I=G();if(n){var J=!!(n.location.protocol==Lb||n.location.protocol==Mb);n.__gwt_activeModules[S].canRedirect=J;if(J){var K=Nb;var L=n.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(Ob+L)}L=db}if(L&&!n[K]){n[K]=true;n[K+Pb]=D();var M=o.createElement(Y);M.src=L;var N=o.getElementsByTagName(Fb)[0];N.insertBefore(M,N.firstElementChild||N.children[0]);return false}}}H();q(O,Kb);B(I);return true}
devhttpclient.succeeded=devhttpclient();